apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expense-ebs-sc
reclaimPolicy: Retain
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer # storage/volume is created automatically when pod is created so PV is also cretaed automatically by SC