apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-efs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d27e144061967bfa
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-efs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: expense-efs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static
  labels:
    purpose: efs-static
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: efs-static-5gi
      mountPath: /usr/share/nginx/html
  volumes:
  - name: efs-static-5gi
    persistentVolumeClaim:
      claimName: expense-efs
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    purpose: efs-static
  ports:
  - name: nginx-nodeport
    protocol: TCP
    port: 80 #service port
    targetPort: 80 # container port
    nodePort: 30007