apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  selector:
    project: expense
    module: backend
  ports:
  - name: nginx-nodeport
    protocol: TCP
    port: 80 #service port
    targetPort: 80 # container port


