apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    project: expense
    module: backend
  ports:
  - name: nginx-LB
    protocol: TCP
    port: 80 #service port
    targetPort: 80 # container port


