apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-RPS
  labels: # replicaset labels
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels: # selector labels
      tier: frontend
      app: nginx
  template:
    metadata:
      labels: # pod labels
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
