apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: # replicaset labels
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels: # selector labels
      tier: frontend
      app: nginx
  template:
    metadata:
      labels: # pod labels
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine3.20
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    tier: frontend
    app: nginx
  ports:
  - name: nginx-serviceport
    protocol: TCP
    port: 80 #service port
    targetPort: 80 # container port